{% set name = "rejected" %}
{% set version = "3.20.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rejected/{{ name }}-{{ version }}.tar.gz
  sha256: d66c7bc00dae9987534d1c20fb644aea8de899962c137edcf1363196710ed7e3

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed . -vvv
  entry_points:
    - rejected = rejected.controller:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<5

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - xhochy
