{% set name = "rejected" %}
{% set version = "3.19.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/rejected/{{ name }}-{{ version }}.tar.gz
  sha256: 60e85b2b572716ef2062eb9e7e34f2cc6a2ed18afed5d741d582cee0cd8ded30

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed . -vvv
  entry_points:
    - rejected = rejected.controller:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<5

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD 3-clause
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - xhochy
