{% set name = "rejected" %}
{% set version = "3.22.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rejected/{{ name }}-{{ version }}.tar.gz
  sha256: f352b960069480ebe9ce26fae18c3b46f9690e2bf8c63e31df887c93a8e226ab

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed . -vvv
  entry_points:
    - rejected = rejected.controller:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<5

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - xhochy
