{% set version = "3.19.9" %}

package:
  name: rejected
  version: {{ version }}

source:
  fn: rejected-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/rejected/rejected-{{ version }}.tar.gz
  md5: 61ed010ea30278d8cadbccabb4c4bc0b

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - rejected = rejected.controller:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - setuptools
    - flatdict >=3,<4
    - helper >2.4,<3
    - ietfparse >=1.5.0,<2
    - pika >=0.10.0,<1
    - psutil >=5,<6
    - pyyaml >=3,<4
    - tornado >=4.2,<5

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD 3-clause
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - frol
