{% set name = "rejected" %}
{% set version = "3.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rejected/{{ name }}-{{ version }}.tar.gz
  sha256: bdcb74654429fdf447711db9ecc91b6c8ba3d32ae60c26c59eced0852f4f6aa8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed . -vvv
  entry_points:
    - rejected = rejected.controller:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<5

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - xhochy
