{% set version = "3.19.8" %}

package:
  name: rejected
  version: {{ version }}

source:
  fn: rejected-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/rejected/rejected-{{ version }}.tar.gz
  md5: 21d1ba86866290670376527fd7cc7c4f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - rejected = rejected.controller:main

requirements:
  build:
    - python
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<4.3

  run:
    - python
    - setuptools
    - helper
    - pika >=0.10.0
    - psutil
    - pyyaml
    - tornado >=4.2,<4.3

test:
  imports:
    - rejected
  commands:
    - rejected --help

about:
  home: https://rejected.readthedocs.io
  license: BSD 3-clause
  summary: An AMQP (RabbitMQ) consumer daemon and message processing framework

extra:
  recipe-maintainers:
    - frol
