travis:
  secure:
    BINSTAR_TOKEN: IrozpGxcbzUfoMw3lnJ44DyiE86aSg14OKcVXDnaw4w8j/So0lLpXgX4ppTPI3gazRYOu7w9TGWq211q38WpOx/k01taaQO3xbQOh9I6tkxBrL5xIsgUkt6zclOoQTurYsyXDBcFzOngVrAu0WJ4wbCcwm/KDo53qiGvVNVs4HrM9CrX805CUDje8uxjS+BT5QUPtm1oN83JEkU/GFlEZL1encZsUHZiIK7J5zbrsIiUMLJoApXhYfBGR+JRum7xr5FXeeqMPWXY3Vw93KMfr8qK1XlxpW+xuiVrJoTS7pWODBL77jdMO+kuHrQZmoUSLgH6rbTDDxibRKw7dJD/ZMfEMWd/IoMrvgMFXaxNQKTNYEUsKKdTiEf3h3A3EhNqW+KBXMTk1bVxjthXPq04dB18hLjT19gNktNgSIJ443S0a0Q56ZaGHGv6XOHSLOf+IfvfJ4ilS3RZEWxc2Wjsc9zhf/2IiFLVKlHRgIzecQxl1cDmzeJudIljg3j2g6zI8izU8WDIl1XErsuw6HTR5UqE/T5oIEG1GPqBbUuoiTE8TVrof3ktkPCTI3LBj33F2NOe9nDeskbNYUmuit6gziJGZeXdWYn/8C5Hj3/+91wj5mz+bkA90f5gEbi82/79gMAPKURLhEdEXLYZrMFc1HY5YlAbkN2E4Td40L1N4vs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
