appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OiiEhHdeP/XLEB0bXrvG44WipE0blMUsoQx3qWRXkvf42MxjNJHNoqdsvOgcUIYpc1XtkHzpU9X1pYxtk4RxEcvP5LijT4CXOZ2Am8NKniSQcnsysYKyK9JeV3Tmm+IkxXFd9mJP4bBaNHZPTYU4bGHKYQmWeg7DdsR2U1ptE/hN3LUyq+mYOZ1A9PpyDYhCJjQJwVJ5rRvR+k9BjFeV3KNYRz2Rxl+1sLCi18toK24P2bg26T51wNC2oU3GSLe8T8EfHxtk4plSlLdZkJHKFBcntFi1EObh1o7dyb14MP9pLU1KBcRzNldUN6LHbM/vMnJT/f/RSdiBQGWxHMVO2HGoG4WKpXDXi7jJjFknOguEjhxsCUej0tyC+hVxU8/pSMiniwLl9/zr7wxxwPkFv0oS1SeMy+F/QPoEy6GAL8FGFdRYW1aQSAdOC/CEzL2rAAA2oYSXI7MJxhgVg5CRvMUgxvxqPOKCPM8SwYpr3xv/kXlBYO9p6g9ERIYnvvC+8MPxHS5h/f66Ttuuor3znZNezSHf9WfWKEb91LK3lapO0pX0/Sv54gBkQIzWDaaMpCRpGlbk6rsU/Wt2ay9LcWSzYkuMl29OCbX6dPrfPAXYD6Cb/dtWhJtAy4grdpgp1+5FAKGMMM38EazJ4La1ucJnKLZpnFHbzSznLKUW/Qg=}
conda_forge_output_validation: true
